# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024-2026 David Kleinhans, Jade University of Applied Sciences
"""
Django settings for the DeepL Translation Frontend.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Security Settings
# =================

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment variable (set by entrypoint.sh from file)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    # Fallback: try reading directly from file (for local development)
    secret_key_file = os.getenv("SECRET_KEY_FILE", "/secrets/django_secret_key")
    if os.path.exists(secret_key_file):
        with open(secret_key_file, 'r') as f:
            SECRET_KEY = f.read().strip()
    else:
        # Last resort: use SECRET_KEY env var (deprecated)
        SECRET_KEY = os.getenv("SECRET_KEY", "")

if not SECRET_KEY:
    raise ValueError(
        "Django SECRET_KEY not found. Either:\n"
        "  1. Set DJANGO_SECRET_KEY environment variable, or\n"
        "  2. Create a secret key file at SECRET_KEY_FILE path, or\n"
        "  3. Let entrypoint.sh generate it automatically (recommended)"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")

# Get DeepL API key from environment
DEEPL_AUTHKEY = os.getenv("DEEPL_AUTHKEY", "")
if not DEEPL_AUTHKEY:
    raise ValueError("DEEPL_AUTHKEY environment variable must be set")

# Application Branding Configuration
# ===================================

# Application title (displayed in browser tab) - supports multiple languages
APP_TITLE_EN = os.getenv("APP_TITLE_EN", "DeepL Translation Frontend")
APP_TITLE_DE = os.getenv("APP_TITLE_DE", "DeepL Übersetzungs-Frontend")

# Organization name (displayed in footer, empty to hide) - supports multiple languages
ORGANIZATION_NAME_EN = os.getenv("ORGANIZATION_NAME_EN", "")
ORGANIZATION_NAME_DE = os.getenv("ORGANIZATION_NAME_DE", "")

# Footer text (use {year} for current year placeholder)
FOOTER_TEXT = os.getenv("FOOTER_TEXT", "{year}+ Translation Service")

# Logo configuration
LOGO_FILENAME = os.getenv("LOGO_FILENAME", "")  # Filename in static/logo/
LOGO_MAX_WIDTH = int(os.getenv("LOGO_MAX_WIDTH", "250"))  # Maximum width in pixels

# Corporate Identity - Colors (hex codes without #)
# These colors are used throughout the UI for consistent branding
PRIMARY_COLOR = os.getenv("PRIMARY_COLOR", "0d6efd")  # Default Bootstrap primary blue
SECONDARY_COLOR = os.getenv("SECONDARY_COLOR", "6610f2")  # Default Bootstrap indigo

# Translation settings
TRANSLATION_DETECTION_LEN = int(os.getenv("TRANSLATION_DETECTION_LEN", "30"))
STATISTICS_DAYS = int(os.getenv("STATISTICS_DAYS", "31"))
STATISTICS_MONTHS = int(os.getenv("STATISTICS_MONTHS", "24"))
STATISTICS_YEARS = int(os.getenv("STATISTICS_YEARS", "5"))

# Allowed hosts - must be set for production
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
# Always include localhost and 127.0.0.1 for Docker health checks
for host in ["localhost", "127.0.0.1"]:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)
if not DEBUG and len(ALLOWED_HOSTS) <= 2:  # Only localhost and 127.0.0.1
    raise ValueError("DJANGO_ALLOWED_HOSTS must be set when DEBUG=False")

# CSRF protection
CSRF_TRUSTED_ORIGINS = [
    origin.strip() 
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") 
    if origin.strip()
]
CSRF_COOKIE_SECURE = not DEBUG  # Require HTTPS for CSRF cookie in production
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookie
CSRF_COOKIE_SAMESITE = "Lax"  # CSRF cookie sent only with same-site requests

# Session security
SESSION_COOKIE_SECURE = not DEBUG  # Require HTTPS for session cookie in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = "Lax"  # Session cookie sent only with same-site requests
SESSION_COOKIE_AGE = 3600  # Session expires after 1 hour of inactivity

# Security headers
SECURE_BROWSER_XSS_FILTER = True  # Enable browser's XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
X_FRAME_OPTIONS = "DENY"  # Prevent clickjacking

# SSL/HTTPS settings (when behind reverse proxy)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# In production, enforce HTTPS
if not DEBUG:
    SECURE_SSL_REDIRECT = False  # Handled by nginx
    SECURE_HSTS_SECONDS = 31536000  # Enable HSTS for 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "deeplFrontend",
    "crispy_forms",
    "crispy_bootstrap5",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.app_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database file location (Docker volume-mounted to /app/data/db)
DATABASE_DIR = BASE_DIR / "data" / "db"
os.makedirs(DATABASE_DIR, exist_ok=True)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(DATABASE_DIR, "db.sqlite3"),
        # SQLite optimization settings for production
        "OPTIONS": {
            "timeout": 20,  # Wait up to 20 seconds for locks
        },
    }
}

# SQLite PRAGMA settings - applied via signal
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def set_sqlite_pragma(sender, connection, **kwargs):
    """Set SQLite PRAGMA settings for better performance."""
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        cursor.execute('PRAGMA journal_mode=WAL;')  # Write-Ahead Logging for better concurrency
        cursor.execute('PRAGMA synchronous=NORMAL;')  # Balance between safety and performance
        cursor.execute('PRAGMA cache_size=-64000;')  # 64MB cache
        cursor.execute('PRAGMA temp_store=MEMORY;')  # Store temp tables in memory
        cursor.close()


# Logging Configuration
# =====================

# Get log level from environment (default: INFO)
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "deeplFrontend": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": LOG_LEVEL,
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGES = [
    ("en", _("English")),
    ("de", _("German")),
]
LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "en-us")

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")

STATICFILES_DIRS = [
    BASE_DIR / "static",  # For additional static files in development
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
