# Generated by Django 4.2 on 2023-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Time stamp"),
                ),
                (
                    "characters",
                    models.IntegerField(
                        verbose_name="Characters sent to DeepL for translation"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        max_length=20,
                        verbose_name="Direction of Translation after auto detection",
                    ),
                ),
                (
                    "auto_detection",
                    models.BooleanField(
                        verbose_name="Auto detection of language used?"
                    ),
                ),
            ],
        ),
    ]
