# Generated by Django 4.2 on 2025-12-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeplFrontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glossary_id', models.CharField(help_text='The unique identifier returned by DeepL API', max_length=255, unique=True, verbose_name='DeepL Glossary ID')),
                ('name', models.CharField(help_text='Human-readable name for the glossary', max_length=255, verbose_name='Glossary Name')),
                ('source_lang', models.CharField(help_text='Source language code (e.g., DE, EN)', max_length=10, verbose_name='Source Language')),
                ('target_lang', models.CharField(help_text='Target language code (e.g., EN-GB, DE)', max_length=10, verbose_name='Target Language')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='When the glossary was uploaded to DeepL', verbose_name='Upload Date')),
                ('original_filename', models.CharField(help_text='The original CSV filename', max_length=255, verbose_name='Original Filename')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional description or notes about this glossary', verbose_name='Comment')),
                ('entry_count', models.IntegerField(default=0, help_text='Number of entries in the glossary', verbose_name='Entry Count')),
            ],
            options={
                'verbose_name': 'Glossary',
                'verbose_name_plural': 'Glossaries',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['-timestamp'], name='deeplFronte_timesta_437716_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['direction'], name='deeplFronte_directi_5d6c15_idx'),
        ),
        migrations.AddIndex(
            model_name='glossary',
            index=models.Index(fields=['glossary_id'], name='deeplFronte_glossar_f179a5_idx'),
        ),
        migrations.AddIndex(
            model_name='glossary',
            index=models.Index(fields=['source_lang', 'target_lang'], name='deeplFronte_source__4ee71d_idx'),
        ),
    ]
