# Generated by Django 5.2.11 on 2026-04-14 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeplFrontend', '0002_glossary_alter_translation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTranslationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, help_text='Django session key of the user who started the job', max_length=40, verbose_name='Session key')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original filename')),
                ('file_type', models.CharField(help_text='Extension, e.g. .docx or .pptx', max_length=10, verbose_name='File type')),
                ('file_size', models.PositiveIntegerField(verbose_name='File size (bytes)')),
                ('direction', models.CharField(max_length=20, verbose_name='Translation direction')),
                ('characters', models.PositiveIntegerField(default=0, verbose_name='Characters translated')),
                ('api_calls', models.PositiveIntegerField(default=0, verbose_name='API calls')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Translation duration (seconds)')),
                ('output_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Output filename')),
                ('result_path', models.CharField(blank=True, default='', max_length=512, verbose_name='Result file path')),
                ('downloaded', models.BooleanField(default=False, verbose_name='Downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Translation Job',
                'verbose_name_plural': 'Document Translation Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='deeplFronte_session_0c0a01_idx'), models.Index(fields=['status'], name='deeplFronte_status_04adb0_idx')],
            },
        ),
    ]
