# Generated by Django 5.2.11 on 2026-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeplFrontend', '0003_document_translation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttranslationjob',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Download count'),
        ),
        migrations.AddField(
            model_name='translation',
            name='is_document_translation',
            field=models.BooleanField(default=False, verbose_name='Document translation?'),
        ),
    ]
